version: "3.8"
services:
  postgres:
    image: "postgres:14.1"
    container_name: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  mongo:
    image: mongo
#    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"